"""initial schema: users, scan_jobs, scan_results, dead_symbols

Revision ID: 8117e4fbfb25
Revises: 
Create Date: 2026-07-04 17:49:33.305341

NOTE ON DOWNGRADE: Postgres ENUM types (scan_job_status here) aren't owned
by any one table, so `downgrade()` drops the tables but can leave the ENUM
type behind if a later revision's upgrade() tries to recreate it -- you'll
see "type already exists". Tested locally; if you hit that, drop the type
by hand (`DROP TYPE scan_job_status;`) before re-running upgrade. Doesn't
affect upgrade() or normal forward migrations, only a downgrade-then-
upgrade cycle.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8117e4fbfb25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_symbols',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strike_count', sa.Integer(), nullable=False),
    sa.Column('first_strike_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_strike_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('scan_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='scan_job_status'), nullable=False),
    sa.Column('universe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_market_cap', sa.Float(), nullable=False),
    sa.Column('total_stocks', sa.Integer(), nullable=False),
    sa.Column('scanned_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_jobs_status'), 'scan_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_jobs_user_id'), 'scan_jobs', ['user_id'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scan_job_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('rating', sa.String(length=64), nullable=True),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_job_id', 'symbol', name='uq_scan_results_job_symbol')
    )
    op.create_index(op.f('ix_scan_results_qualified'), 'scan_results', ['qualified'], unique=False)
    op.create_index(op.f('ix_scan_results_scan_job_id'), 'scan_results', ['scan_job_id'], unique=False)
    op.create_index(op.f('ix_scan_results_symbol'), 'scan_results', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_results_symbol'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_scan_job_id'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_qualified'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_scan_jobs_user_id'), table_name='scan_jobs')
    op.drop_index(op.f('ix_scan_jobs_status'), table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('dead_symbols')
    # ### end Alembic commands ###
